import Link from "next/link";
import {
  AlertTriangle,
  ArrowRight,
  CheckCircle2,
  FileWarning,
  GitCompareArrows,
  Lock,
  PenLine,
  Search,
  ShieldCheck,
  ShieldX,
  Wifi,
  Zap,
} from "lucide-react";
import { MarketingHeader } from "@/components/MarketingHeader";
import { MarketingFooter } from "@/components/MarketingFooter";
import { Button } from "@/components/ui/button";

// Same content as the internal "How TaxFlow actually works" explainer, but
// rebuilt as a scannable product page instead of a long-form essay - a
// time-poor practitioner deciding whether to trust this tool skims a page,
// they don't read six paragraphs of prose before their first click. The
// pipeline is a visual stepper, the worked example is an actual chat mockup
// (not a quote block), and the honest tone/content is unchanged - only the
// shape changed. Data residency has its own full treatment on /about, so
// this only summarises it with a link rather than repeating it.
const PIPELINE = [
  {
    icon: Search,
    title: "Retrieval",
    tagline: "Find the real source material first",
    detail:
      "Your question searches a knowledge base of real ATO rulings, determinations, and legislation - hybrid semantic + keyword search, re-ranked, not one vector lookup.",
    points: [
      "Weighted toward the right state/jurisdiction, without hard-excluding others",
      "One long Act can't crowd out a shorter, more on-point ruling",
      "Your firm's own precedents compete in the same ranked pool, not bolted on after",
      "Superseded law is retrieved separately, down-weighted, and labelled historical",
    ],
  },
  {
    icon: Zap,
    title: "Routing",
    tagline: "The model is chosen by the question",
    detail:
      "A fast, cheap model handles most questions. TaxFlow escalates to a stronger model automatically when retrieval signals say the question is hard - you never pick a \"mode.\"",
    points: [],
  },
  {
    icon: PenLine,
    title: "Generation",
    tagline: "Drafted strictly from what retrieval found",
    detail:
      "Every factual claim carries a numbered citation. When the sources don't cover the question, TaxFlow is instructed to say so - not fill the gap from general training knowledge.",
    points: [],
  },
  {
    icon: ShieldCheck,
    title: "Verification",
    tagline: "A second, independent pass checks the first",
    detail:
      "A separate model call - different prompt, acting as a senior reviewer, given only the draft and the sources - checks every claim and returns a graded verdict: critical, warning, or note.",
    points: [],
  },
] as const;

const CHECKS = [
  {
    icon: AlertTriangle,
    title: "Factual accuracy",
    body: "The reviewer is given the exact source text and the exact claim, and asked whether it's supported - graded critical (wrong rate/section/test), warning (misleading or incomplete), or note (minor).",
  },
  {
    icon: GitCompareArrows,
    title: "Topic mismatch",
    body: "A fluent answer can cite real documents that are simply about the wrong area of law - a payroll-tax ruling backing an FBT question. TaxFlow classifies the topic of the question and every cited source separately, and treats a mismatch as an automatic trigger regardless of how confident the answer sounds.",
  },
  {
    icon: ShieldX,
    title: "When it runs",
    body: "Verification is gated to answers with real risk signals - low confidence, few citations, an explicit \"sources don't cover this\" admission, or a topic mismatch. A confident, well-cited, on-topic answer skips the slower check.",
  },
];

const ROLES = [
  { name: "Staff", can: ["Ask questions, draft documents"], cannot: "Cannot approve or finalise anything" },
  { name: "Reviewer", can: ["Everything Staff can do", "Approve and finalise documents & ATO responses"], cannot: null },
  {
    name: "Owner",
    can: ["Everything Reviewer can do", "Manage firm knowledge, staff, and billing"],
    cannot: "A firm can never remove its last active Owner",
  },
];

const LIMITS = [
  {
    title: "Not a substitute for professional judgement",
    body: "Every draft carries an explicit limitation note. The ATO has stated relying on AI-generated advice isn't a reasonable excuse for an error - this is built with that standard in mind.",
  },
  {
    title: "Knowledge base coverage has real gaps",
    body: "Coverage grows over time; it isn't complete today. TaxFlow tells you when a question falls outside it, rather than guessing.",
  },
  {
    title: "Verification isn't infallible",
    body: "It's a second model call checking a first one, not a formal proof of correctness. It substantially reduces the risk of an unreviewed error reaching you - it doesn't remove the need for review.",
  },
  {
    title: "Depends on third-party AI providers",
    body: "Answers are generated by external LLM providers. A provider-side outage can cause a question to fail outright - error handling for that is active, ongoing work.",
  },
];

export default function HowItWorksPage() {
  return (
    <>
      <MarketingHeader />
      <main className="flex-1 bg-background">
        {/* Hero */}
        <section className="border-b border-border bg-muted/30 px-6 py-20">
          <div className="mx-auto max-w-3xl text-center">
            <span className="mb-3 block text-xs font-semibold uppercase tracking-widest text-accent">
              For practitioners, by design
            </span>
            <h1 className="mb-5 text-3xl font-bold leading-tight text-foreground md:text-4xl">
              How TaxFlow actually works
            </h1>
            <p className="mx-auto max-w-xl text-lg leading-relaxed text-muted-foreground">
              Written for accountants who&apos;ve been burned by AI before. No black box - every
              mechanism below is the real one, including the parts that sometimes fail and the
              parts we haven&apos;t built yet.
            </p>
          </div>
        </section>

        {/* Pipeline */}
        <section className="px-6 py-20">
          <div className="mx-auto max-w-5xl">
            <div className="mb-12 max-w-2xl">
              <span className="mb-3 block text-xs font-semibold uppercase tracking-widest text-accent">
                01 · Your question, end to end
              </span>
              <h2 className="mb-3 text-2xl font-bold text-foreground md:text-3xl">
                Four stages, each inspectable - not one opaque model call
              </h2>
            </div>

            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              {PIPELINE.map((step, i) => (
                <div key={step.title} className="rounded-xl border border-border bg-card p-6">
                  <div className="mb-4 flex items-center gap-3">
                    <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-accent/10 text-accent">
                      <step.icon className="h-5 w-5" />
                    </div>
                    <div>
                      <span className="block text-xs font-semibold text-muted-foreground">
                        Step {i + 1}
                      </span>
                      <h3 className="text-lg font-bold text-foreground">{step.title}</h3>
                    </div>
                  </div>
                  <p className="mb-2 text-sm font-medium text-foreground">{step.tagline}</p>
                  <p className="mb-3 text-sm leading-relaxed text-muted-foreground">{step.detail}</p>
                  {step.points.length > 0 && (
                    <ul className="space-y-1.5">
                      {step.points.map((p) => (
                        <li key={p} className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
                          <span className="mt-1 h-1 w-1 shrink-0 rounded-full bg-accent" />
                          {p}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Verification checks */}
        <section className="border-y border-border bg-muted/30 px-6 py-20">
          <div className="mx-auto max-w-5xl">
            <div className="mb-12 max-w-2xl">
              <span className="mb-3 block text-xs font-semibold uppercase tracking-widest text-accent">
                02 · What verification is actually checking for
              </span>
              <h2 className="text-2xl font-bold text-foreground md:text-3xl">
                Three specific failure modes - not a generic &quot;fact check&quot;
              </h2>
            </div>

            <div className="mb-8 grid grid-cols-1 gap-6 md:grid-cols-3">
              {CHECKS.map((c) => (
                <div key={c.title} className="rounded-xl border border-border bg-card p-6">
                  <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10 text-accent">
                    <c.icon className="h-5 w-5" />
                  </div>
                  <h3 className="mb-2 text-base font-bold text-foreground">{c.title}</h3>
                  <p className="text-sm leading-relaxed text-muted-foreground">{c.body}</p>
                </div>
              ))}
            </div>

            <div className="rounded-xl border border-accent/20 bg-accent/5 p-5 text-sm leading-relaxed text-foreground">
              <b className="text-accent">When something critical is found:</b> it triggers a
              corrective regeneration - TaxFlow attempts to fix the answer with a widened source
              pool before you ever see it. What you see is the result after that correction loop
              has already run once.
            </div>
          </div>
        </section>

        {/* Worked example, as an actual chat mock */}
        <section className="px-6 py-20">
          <div className="mx-auto max-w-3xl">
            <div className="mb-10 max-w-2xl">
              <span className="mb-3 block text-xs font-semibold uppercase tracking-widest text-accent">
                03 · A real answer, not a demo one
              </span>
              <h2 className="text-2xl font-bold text-foreground md:text-3xl">
                Taken from a live session - including where it stopped short
              </h2>
            </div>

            <div className="overflow-hidden rounded-xl border border-border bg-card shadow-sm">
              <div className="border-b border-border bg-muted/40 px-5 py-3">
                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  Question asked
                </p>
              </div>
              <div className="border-b border-border px-5 py-4">
                <p className="text-sm italic leading-relaxed text-muted-foreground">
                  &quot;One of our partner entities is a small business entity with turnover under
                  $2M - does it qualify for the 50% CGT discount plus the small business 50%
                  reduction on the sale of its interest in the development?&quot;
                </p>
              </div>
              <div className="space-y-4 px-5 py-5">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-700 dark:bg-amber-500/10 dark:text-amber-400">
                    <ShieldCheck className="h-3 w-3" /> Verified against sources
                  </span>
                  <span className="text-xs text-muted-foreground">Used 5 sources</span>
                </div>
                <p className="text-sm leading-relaxed text-foreground">
                  &quot;Based on the provided sources, I cannot give you a complete answer to this
                  question because the sources do not address capital gains tax (CGT) concessions
                  or the 50% CGT discount and small business 50% reduction you mention.
                </p>
                <p className="text-sm leading-relaxed text-foreground">
                  The provided documents (
                  <span className="rounded bg-blue-50 px-1 font-mono text-xs text-blue-700 dark:bg-blue-500/10 dark:text-blue-400">1</span>
                  –
                  <span className="rounded bg-emerald-50 px-1 font-mono text-xs text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-400">8</span>
                  ) focus exclusively on the definition of &apos;small business entity&apos; under
                  Subdivision 328-C... they do not contain the CGT-specific rules that govern
                  whether a small business entity qualifies for the 50% CGT discount.&quot;
                </p>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  The answer then states plainly what the sources <i>do</i> confirm, and recommends
                  which legislation (Division 152 ITAA 1997) and action (a Private Binding Ruling,
                  if complex) to pursue instead.
                </p>
              </div>
            </div>

            <p className="mt-6 text-sm leading-relaxed text-muted-foreground">
              Retrieval found real, correctly-classified sources - they just weren&apos;t the right
              ones for this question, because the knowledge base&apos;s CGT-concession coverage had
              a real gap. TaxFlow didn&apos;t paper over that gap with a fluent guess. It said so,
              and named where to look instead. We&apos;d rather you see this answer than a more
              impressive-looking one that got the legal test wrong.
            </p>
          </div>
        </section>

        {/* Roles / sign-off */}
        <section className="border-y border-border bg-muted/30 px-6 py-20">
          <div className="mx-auto max-w-5xl">
            <div className="mb-10 max-w-2xl">
              <span className="mb-3 block text-xs font-semibold uppercase tracking-widest text-accent">
                04 · Human sign-off is structural
              </span>
              <h2 className="text-2xl font-bold text-foreground md:text-3xl">
                Enforced server-side - not a UI convention a determined user could route around
              </h2>
            </div>

            <div className="flex flex-col items-stretch gap-3 md:flex-row md:items-center">
              {ROLES.map((role, i) => (
                <div key={role.name} className="flex flex-1 items-center gap-3">
                  <div className="flex-1 rounded-xl border border-border bg-card p-5">
                    <h3 className="mb-2 text-base font-bold text-foreground">{role.name}</h3>
                    <ul className="mb-2 space-y-1">
                      {role.can.map((c) => (
                        <li key={c} className="flex items-start gap-1.5 text-xs leading-relaxed text-muted-foreground">
                          <CheckCircle2 className="mt-0.5 h-3 w-3 shrink-0 text-accent" />
                          {c}
                        </li>
                      ))}
                    </ul>
                    {role.cannot && (
                      <p className="text-xs leading-relaxed text-muted-foreground/80">
                        <Lock className="mr-1 inline h-3 w-3" />
                        {role.cannot}
                      </p>
                    )}
                  </div>
                  {i < ROLES.length - 1 && (
                    <ArrowRight className="hidden h-5 w-5 shrink-0 rotate-90 text-muted-foreground md:block md:rotate-0" />
                  )}
                </div>
              ))}
            </div>
            <p className="mt-6 text-sm leading-relaxed text-muted-foreground">
              A junior team member can draft an advice memo at any hour. It doesn&apos;t become the
              firm&apos;s work product until a Reviewer or Owner explicitly approves it - the same
              discipline a paper-based practice already runs, enforced in the software instead of
              left to informal habit.
            </p>
          </div>
        </section>

        {/* Data - summary, links to /about for the full page */}
        <section className="px-6 py-20">
          <div className="mx-auto max-w-3xl">
            <div className="mb-6 flex items-center gap-3">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-accent/10 text-accent">
                <Wifi className="h-5 w-5" />
              </div>
              <h2 className="text-2xl font-bold text-foreground">Where your data actually goes</h2>
            </div>
            <p className="mb-2 text-sm leading-relaxed text-muted-foreground">
              Client records, documents, and firm knowledge are stored and hosted in Australia,
              isolated per firm - never blended into another firm&apos;s answers. Generating an
              answer sends the text of your question to Anthropic&apos;s and OpenAI&apos;s standard
              API infrastructure, which is not Australia-only - that&apos;s genuinely how this
              category of product works today, and we&apos;d rather say so than let you assume
              otherwise.
            </p>
            <Link href="/about" className="text-sm font-medium text-accent hover:underline">
              Read the full data residency page →
            </Link>
          </div>
        </section>

        {/* Limits */}
        <section className="border-t border-border bg-muted/30 px-6 py-20">
          <div className="mx-auto max-w-5xl">
            <div className="mb-10 max-w-2xl">
              <span className="mb-3 block text-xs font-semibold uppercase tracking-widest text-accent">
                05 · What this doesn&apos;t do
              </span>
              <h2 className="text-2xl font-bold text-foreground md:text-3xl">
                Stated as plainly as everything above
              </h2>
              <p className="mt-3 text-sm text-muted-foreground">
                A &quot;how it works&quot; page that only describes strengths isn&apos;t
                transparency, it&apos;s marketing with extra steps. These are real, current
                limitations.
              </p>
            </div>

            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              {LIMITS.map((l) => (
                <div
                  key={l.title}
                  className="rounded-xl border border-amber-300/60 bg-card p-5 dark:border-amber-500/30"
                >
                  <div className="mb-2 flex items-center gap-2">
                    <FileWarning className="h-4 w-4 shrink-0 text-amber-600 dark:text-amber-400" />
                    <h3 className="text-sm font-bold text-foreground">{l.title}</h3>
                  </div>
                  <p className="text-sm leading-relaxed text-muted-foreground">{l.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="bg-primary px-6 py-20 text-primary-foreground">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="mb-4 text-2xl font-bold md:text-3xl">Test it on your own hardest question</h2>
            <p className="mb-8 text-primary-foreground/70">
              That&apos;s the actual point of this page - not to be convinced by us, but to go
              check.
            </p>
            <div className="flex flex-col justify-center gap-4 sm:flex-row">
              <Button asChild size="lg" className="bg-accent text-accent-foreground hover:opacity-90">
                <Link href="/signup">Start your free trial</Link>
              </Button>
              <Button
                asChild
                size="lg"
                variant="outline"
                className="border-primary-foreground/30 bg-transparent text-primary-foreground hover:bg-primary-foreground/10"
              >
                <Link href="/login">Try the live demo</Link>
              </Button>
            </div>
          </div>
        </section>
      </main>
      <MarketingFooter />
    </>
  );
}
