"""Port Protocols for relational data access (repository-per-aggregate).

Replaces the dual Supabase-PostgREST + raw-psycopg2 access with a single
port. Concrete repositories live in ``taxflow.adapters.db.repositories`` and use
the psycopg2 connection pool (``taxflow.db.get_pg_conn``). Every client-scoped
query carries an explicit ``WHERE client_id = %s`` predicate (RLS today keys on
``auth.role() = 'service_role'`` and provides no per-client isolation, so scoping
must live in the query).

Method signatures below are the contract the concrete ``Repositories`` facade
implements; each returns plain dicts/lists matching the shapes routers use today.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ClientsRepo(Protocol):
    def get_by_email(self, email: str) -> dict | None: ...
    def get_by_id(self, client_id: str) -> dict | None: ...
    def create(self, row: dict) -> dict: ...
    def update(self, client_id: str, fields: dict) -> dict | None: ...
    def set_subscription_by_stripe_subscription_id(self, subscription_id: str, fields: dict) -> None: ...
    def set_subscription_by_customer_id(self, customer_id: str, fields: dict) -> None: ...
    def activate_from_checkout(self, client_id: str, fields: dict) -> None: ...
    def find_demo_emails(self, persona: str | None = None) -> list[str]: ...
    def email_exists(self, email: str) -> bool: ...
    def get_voice_sample(self, client_id: str) -> str | None: ...


@runtime_checkable
class TrialsRepo(Protocol):
    def create(self, client_id: str) -> dict: ...
    def latest_for_client(self, client_id: str) -> dict | None: ...
    def increment_usage(self, client_id: str, metric: str) -> None: ...


@runtime_checkable
class QueriesRepo(Protocol):
    def list_recent(self, client_id: str, limit: int) -> list[dict]: ...
    def insert(self, row: dict) -> dict: ...
    def update(self, client_id: str, query_id: str, fields: dict) -> None: ...
    def get_for_client(self, client_id: str, query_id: str) -> dict | None: ...
    def get_question_citations(self, client_id: str, query_id: str) -> dict | None: ...
    def list_session_history(self, client_id: str, session_id: str, limit: int) -> list[dict]: ...
    def set_re_research_status(self, client_id: str, query_id: str, status: str) -> None: ...
    def get_answer_for_client(self, client_id: str, query_id: str) -> dict | None: ...


@runtime_checkable
class QueryFeedbackRepo(Protocol):
    def insert(self, row: dict) -> dict: ...


@runtime_checkable
class DocumentsRepo(Protocol):
    def list_for_client(self, client_id: str, kind_filter: str | None = None) -> list[dict]: ...
    def insert(self, row: dict) -> dict: ...
    def get_for_client(self, client_id: str, document_id: str) -> dict | None: ...
    def update_status(self, client_id: str, document_id: str, status: str, fields: dict | None = None) -> None: ...


@runtime_checkable
class FirmClientsRepo(Protocol):
    def upsert(self, client_id: str, name: str) -> None: ...
    def list_for_client(self, client_id: str, search: str | None = None) -> list[dict]: ...


@runtime_checkable
class QuerySessionsRepo(Protocol):
    def list_for_client(self, client_id: str) -> list[dict]: ...
    def upsert_label(self, client_id: str, session_id: str, label: str) -> dict: ...


@runtime_checkable
class FirmKnowledgeRepo(Protocol):
    def list_for_client(self, client_id: str) -> list[dict]: ...
    def insert(self, row: dict) -> dict: ...
    def get_for_client(self, client_id: str, item_id: str) -> dict | None: ...
    def delete(self, client_id: str, item_id: str) -> None: ...
    def increment_usage(self, client_id: str, item_ids: list[str]) -> None: ...
    def usage_trend(self, client_id: str) -> dict: ...


@runtime_checkable
class KnowledgeSuggestionsRepo(Protocol):
    def insert(self, row: dict) -> dict: ...
    def list_for_client(self, client_id: str, status: str | None = None) -> list[dict]: ...
    def get_for_client(self, client_id: str, suggestion_id: str) -> dict | None: ...
    def set_decision(self, client_id: str, suggestion_id: str, status: str, fields: dict | None = None) -> dict | None: ...
    def approve(self, client_id: str, suggestion_id: str, firm_knowledge_row: dict, decided_by: str | None) -> dict | None: ...
    def exists_for_query(self, client_id: str, query_id: str) -> bool: ...


@runtime_checkable
class EngagementContextRepo(Protocol):
    def insert(self, row: dict) -> dict: ...
    def list_for_client(self, client_id: str, client_ref: str | None = None) -> list[dict]: ...


@runtime_checkable
class RegulatoryAlertsRepo(Protocol):
    def list_recent(self, limit: int) -> list[dict]: ...
    def insert_unseen(self, rows: list[dict]) -> int: ...


@runtime_checkable
class ContactRepo(Protocol):
    def insert(self, row: dict) -> dict: ...


@runtime_checkable
class RateLimitRepo(Protocol):
    def purge_older_than(self, seconds: int) -> None: ...
    def count_hits(self, key: str, window_seconds: int) -> int: ...
    def record_hit(self, key: str) -> None: ...


@runtime_checkable
class QueryCacheRepo(Protocol):
    def get_cached(self, question_norm: str, client_id: str | None, knowledge_version: int) -> dict | None: ...
    def put_cached(self, row: dict) -> None: ...
    def current_knowledge_version(self) -> int: ...
    def bump_knowledge_version(self) -> int: ...
    def count_prior_asks(self, client_id: str, question_norm: str) -> int: ...


@runtime_checkable
class KnowledgeIngestRepo(Protocol):
    def upsert_chunks(self, rows: list[dict]) -> int: ...
    def mark_superseded(self, mapping: dict[str, str]) -> int: ...
    def stale_urls(self, urls: list[str]) -> list[str]: ...
    def graph_metadata(self) -> list[dict]: ...
    def delete_by_source_url(self, source_url: str) -> int: ...
    def list_ingested_sources(self) -> list[dict]: ...


@runtime_checkable
class DemoResetRepo(Protocol):
    def reset_demo_rows(self) -> None: ...


@runtime_checkable
class HealthRepo(Protocol):
    def ping(self) -> bool: ...


@runtime_checkable
class ReResearchJobsRepo(Protocol):
    def enqueue(self, row: dict) -> dict | None: ...
    def claim_next(self) -> dict | None: ...
    def requeue(self, job_id: str, error: str, backoff_seconds: int) -> None: ...
    def mark(self, job_id: str, status: str, fields: dict | None = None) -> None: ...


@runtime_checkable
class NotificationsRepo(Protocol):
    def insert(self, row: dict) -> dict: ...
    def list_for_client(self, client_id: str, limit: int = 50) -> list[dict]: ...
    def mark_read(self, client_id: str, notification_id: str) -> None: ...


@runtime_checkable
class RelationalDataPort(Protocol):
    """Facade exposing one repository per aggregate."""

    clients: ClientsRepo
    trials: TrialsRepo
    queries: QueriesRepo
    query_feedback: QueryFeedbackRepo
    documents: DocumentsRepo
    firm_clients: FirmClientsRepo
    query_sessions: QuerySessionsRepo
    firm_knowledge: FirmKnowledgeRepo
    knowledge_suggestions: KnowledgeSuggestionsRepo
    engagement_context: EngagementContextRepo
    regulatory_alerts: RegulatoryAlertsRepo
    contact: ContactRepo
    rate_limit: RateLimitRepo
    query_cache: QueryCacheRepo
    knowledge_ingest: KnowledgeIngestRepo
    demo_reset: DemoResetRepo
    health: HealthRepo
    re_research_jobs: ReResearchJobsRepo
    notifications: NotificationsRepo


# Convenience alias for adapters that accept extra kwargs dicts.
Row = dict[str, Any]
