"""Port Protocols for relational data access (repository-per-aggregate).

Replaces the dual Supabase-PostgREST + raw-psycopg2 access with a single
port. Concrete repositories live in ``taxflow.adapters.db.repositories`` and use
the psycopg2 connection pool (``taxflow.db.get_pg_conn``). Every client-scoped
query carries an explicit ``WHERE client_id = %s`` predicate (RLS today keys on
``auth.role() = 'service_role'`` and provides no per-client isolation, so scoping
must live in the query).

Method signatures below are the contract the concrete ``Repositories`` facade
implements; each returns plain dicts/lists matching the shapes routers use today.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ClientsRepo(Protocol):
    def get_by_email(self, email: str) -> dict | None: ...
    def get_by_id(self, client_id: str) -> dict | None: ...
    def create(self, row: dict) -> dict: ...
    def update(self, client_id: str, fields: dict) -> dict | None: ...
    def set_subscription_by_stripe_subscription_id(self, subscription_id: str, fields: dict) -> None: ...
    def set_subscription_by_customer_id(self, customer_id: str, fields: dict) -> None: ...
    def activate_from_checkout(self, client_id: str, fields: dict) -> None: ...
    def find_demo_emails(self, persona: str | None = None) -> list[str]: ...
    def email_exists(self, email: str) -> bool: ...
    def get_voice_sample(self, client_id: str) -> str | None: ...


@runtime_checkable
class UsersRepo(Protocol):
    """Individual logins within a firm (migration 043). ``id`` is the Supabase
    Auth user id (JWT ``sub``) — the stable identity key auth resolves by."""

    def get_by_id(self, user_id: str) -> dict | None: ...
    def get_by_client_and_email(self, client_id: str, email: str) -> dict | None: ...
    def create(
        self,
        user_id: str,
        client_id: str,
        email: str,
        role: str = "owner",
        display_name: str | None = None,
        invited_by: str | None = None,
        status: str = "active",
    ) -> dict: ...
    def list_for_client(self, client_id: str) -> list[dict]: ...
    def update_role(self, client_id: str, user_id: str, role: str) -> dict | None: ...
    def set_status(self, client_id: str, user_id: str, status: str) -> dict | None: ...
    def count_active_owners(self, client_id: str) -> int: ...


@runtime_checkable
class TrialsRepo(Protocol):
    def create(self, client_id: str) -> dict: ...
    def latest_for_client(self, client_id: str) -> dict | None: ...
    def increment_usage(self, client_id: str, metric: str) -> None: ...


@runtime_checkable
class QueriesRepo(Protocol):
    def list_recent(self, client_id: str, limit: int) -> list[dict]: ...
    def insert(self, row: dict) -> dict: ...
    def update(self, client_id: str, query_id: str, fields: dict) -> None: ...
    def delete(self, client_id: str, query_id: str) -> None: ...
    def delete_session(self, client_id: str, session_id: str) -> bool: ...
    def get_for_client(self, client_id: str, query_id: str) -> dict | None: ...
    def get_question_citations(self, client_id: str, query_id: str) -> dict | None: ...
    def list_session_history(self, client_id: str, session_id: str, limit: int) -> list[dict]: ...
    def count_session_clarifications(self, client_id: str, session_id: str) -> int: ...
    def set_re_research_status(self, client_id: str, query_id: str, status: str) -> None: ...
    def get_answer_for_client(self, client_id: str, query_id: str) -> dict | None: ...
    def stats(self, start, end=None, client_id=None) -> dict: ...


@runtime_checkable
class QueryFeedbackRepo(Protocol):
    def insert(self, row: dict) -> dict: ...


@runtime_checkable
class AnnotationsRepo(Protocol):
    """Polymorphic line/word-level annotations & comments (migration 038).

    Every method is client_id-scoped — RLS provides no tenant isolation, so the
    ``WHERE client_id = %s`` predicate on each statement is the only boundary.
    """

    def list_for_target(self, client_id: str, target_type: str, target_id: str) -> list[dict]: ...
    def insert(self, row: dict) -> dict: ...
    def get_for_client(self, client_id: str, annotation_id: str) -> dict | None: ...
    def update(self, client_id: str, annotation_id: str, fields: dict) -> dict | None: ...
    def delete(self, client_id: str, annotation_id: str) -> None: ...


@runtime_checkable
class DocumentsRepo(Protocol):
    def list_for_client(self, client_id: str, kind_filter: str | None = None) -> list[dict]: ...
    def insert(self, row: dict) -> dict: ...
    def get_for_client(self, client_id: str, document_id: str) -> dict | None: ...
    def update_status(self, client_id: str, document_id: str, status: str, fields: dict | None = None) -> None: ...
    def update(self, client_id: str, document_id: str, fields: dict) -> dict | None: ...
    def delete(self, client_id: str, document_id: str) -> None: ...


@runtime_checkable
class FirmClientsRepo(Protocol):
    def upsert(self, client_id: str, name: str) -> None: ...
    def create(self, client_id: str, name: str) -> dict: ...
    def list_for_client(self, client_id: str, search: str | None = None) -> list[dict]: ...
    def list_directory(self, client_id: str) -> list[dict]: ...


@runtime_checkable
class EngagementsRepo(Protocol):
    """First-class engagements (migration 039).

    Every method is client_id-scoped — RLS provides no tenant isolation, so the
    ``WHERE client_id = %s`` predicate on each statement is the only boundary.
    ``create`` allocates the per-firm-client sequential ``engagement_number`` and
    inserts the engagement in a single transaction; it raises when the target
    firm-client is unknown or belongs to another tenant.
    """

    def create(self, client_id: str, firm_client_id: str, description: str, created_by: str | None = None) -> dict: ...
    def list_for_client(self, client_id: str, firm_client_id: str | None = None, status: str | None = None) -> list[dict]: ...
    def get_for_client(self, client_id: str, engagement_id: str) -> dict | None: ...


@runtime_checkable
class EngagementBackfillRepo(Protocol):
    """Read/link helpers for the one-time engagement backfill (migration 039
    follow-up). Client-scoped and idempotent (only rows with
    ``engagement_id IS NULL`` are ever touched)."""

    def distinct_unlinked_buckets(self, client_id: str | None = None) -> list[dict]: ...
    def link_bucket(self, client_id: str, client_ref: str | None, engagement_id: str) -> int: ...


@runtime_checkable
class QuerySessionsRepo(Protocol):
    def list_for_client(self, client_id: str) -> list[dict]: ...
    def upsert_label(self, client_id: str, session_id: str, label: str) -> dict: ...


@runtime_checkable
class DocumentTemplatesRepo(Protocol):
    def list_for_client(self, client_id: str) -> list[dict]: ...
    def get_for_key(self, client_id: str, template_key: str) -> dict | None: ...
    def upsert(
        self, client_id: str, template_key: str, body: str, updated_by: str | None = None
    ) -> dict: ...
    def delete(self, client_id: str, template_key: str) -> None: ...


@runtime_checkable
class FirmKnowledgeRepo(Protocol):
    def list_for_client(self, client_id: str) -> list[dict]: ...
    def insert(self, row: dict) -> dict: ...
    def get_for_client(self, client_id: str, item_id: str) -> dict | None: ...
    def delete(self, client_id: str, item_id: str) -> bool: ...
    def update(self, client_id: str, item_id: str, content: str, embedding: list[float]) -> dict | None: ...
    def increment_usage(self, client_id: str, item_ids: list[str]) -> None: ...
    def usage_trend(self, client_id: str) -> dict: ...


@runtime_checkable
class KnowledgeSuggestionsRepo(Protocol):
    def insert(self, row: dict) -> dict: ...
    def list_for_client(self, client_id: str, status: str | None = None) -> list[dict]: ...
    def get_for_client(self, client_id: str, suggestion_id: str) -> dict | None: ...
    def set_decision(self, client_id: str, suggestion_id: str, status: str, fields: dict | None = None) -> dict | None: ...
    def approve(self, client_id: str, suggestion_id: str, firm_knowledge_row: dict, decided_by: str | None) -> dict | None: ...
    def exists_for_query(self, client_id: str, query_id: str) -> bool: ...


@runtime_checkable
class EngagementContextRepo(Protocol):
    def insert(self, row: dict) -> dict: ...
    def list_for_client(self, client_id: str, client_ref: str | None = None) -> list[dict]: ...


@runtime_checkable
class RegulatoryAlertsRepo(Protocol):
    def list_recent(self, limit: int) -> list[dict]: ...
    def insert_unseen(self, rows: list[dict]) -> int: ...


@runtime_checkable
class ContactRepo(Protocol):
    def insert(self, row: dict) -> dict: ...


@runtime_checkable
class RateLimitRepo(Protocol):
    def purge_older_than(self, seconds: int) -> None: ...
    def count_hits(self, key: str, window_seconds: int) -> int: ...
    def record_hit(self, key: str) -> None: ...


@runtime_checkable
class QueryCacheRepo(Protocol):
    def get_cached(self, question_norm: str, client_id: str | None, knowledge_version: int) -> dict | None: ...
    def put_cached(self, row: dict) -> None: ...
    def current_knowledge_version(self) -> int: ...
    def bump_knowledge_version(self) -> int: ...
    def count_prior_asks(self, client_id: str, question_norm: str) -> int: ...
    def invalidate(self, client_id: str, question_norm: str) -> None: ...


@runtime_checkable
class KnowledgeIngestRepo(Protocol):
    def upsert_chunks(self, rows: list[dict]) -> int: ...
    def mark_superseded(self, mapping: dict[str, str]) -> int: ...
    def stale_urls(self, urls: list[str]) -> list[str]: ...
    def graph_metadata(self) -> list[dict]: ...
    def delete_by_source_url(self, source_url: str) -> int: ...
    def list_ingested_sources(self) -> list[dict]: ...


@runtime_checkable
class DemoResetRepo(Protocol):
    def reset_demo_rows(self) -> None: ...


@runtime_checkable
class HealthRepo(Protocol):
    def ping(self) -> bool: ...


@runtime_checkable
class ReResearchJobsRepo(Protocol):
    def enqueue(self, row: dict) -> dict | None: ...
    def claim_next(self) -> dict | None: ...
    def requeue(self, job_id: str, error: str, backoff_seconds: int) -> None: ...
    def mark(self, job_id: str, status: str, fields: dict | None = None) -> None: ...


@runtime_checkable
class NotificationsRepo(Protocol):
    def insert(self, row: dict) -> dict: ...
    def list_for_client(self, client_id: str, limit: int = 50) -> list[dict]: ...
    def mark_read(self, client_id: str, notification_id: str) -> None: ...
    def delete(self, client_id: str, notification_id: str) -> bool: ...


@runtime_checkable
class OpsNotificationsRepo(Protocol):
    def insert(self, row: dict) -> dict: ...
    def latest(self, limit: int = 50) -> list[dict]: ...
    def mark_read(self, notification_id: str) -> None: ...


@runtime_checkable
class ProductionSnapshotsRepo(Protocol):
    def insert(self, row: dict) -> dict: ...
    def latest(self, limit: int = 30) -> list[dict]: ...
    def baseline_window(self, start: Any, end: Any) -> list[dict]: ...


@runtime_checkable
class RelationalDataPort(Protocol):
    """Facade exposing one repository per aggregate."""

    clients: ClientsRepo
    users: UsersRepo
    trials: TrialsRepo
    queries: QueriesRepo
    query_feedback: QueryFeedbackRepo
    annotations: AnnotationsRepo
    documents: DocumentsRepo
    firm_clients: FirmClientsRepo
    engagements: EngagementsRepo
    engagement_backfill: EngagementBackfillRepo
    query_sessions: QuerySessionsRepo
    document_templates: DocumentTemplatesRepo
    firm_knowledge: FirmKnowledgeRepo
    knowledge_suggestions: KnowledgeSuggestionsRepo
    engagement_context: EngagementContextRepo
    regulatory_alerts: RegulatoryAlertsRepo
    contact: ContactRepo
    rate_limit: RateLimitRepo
    query_cache: QueryCacheRepo
    knowledge_ingest: KnowledgeIngestRepo
    demo_reset: DemoResetRepo
    health: HealthRepo
    re_research_jobs: ReResearchJobsRepo
    notifications: NotificationsRepo
    ops_notifications: OpsNotificationsRepo
    production_snapshots: ProductionSnapshotsRepo


# Convenience alias for adapters that accept extra kwargs dicts.
Row = dict[str, Any]
